#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir -p target
            cd src && npm install
      - run:
          name: Package
          command: |
            cd src && zip -r ../target/lambda.zip *
      - persist_to_workspace:
          root: target
          paths:
            - lambda.zip
      - store_artifacts:
          path: target/lambda.zip
  deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: terraform init
      - run: terraform apply -auto-approve -var="version=1.0.${CIRCLE_BUILD_NUM}"

workflows:
  version: 2
  apply:
    jobs:
      - build
      - deploy:
          requires:
            - build
